### ISSUE TITLE
ValueError: cannot find context for 'fork'

### ISSUE THREAD

**Issue by PrasadNR** [lyft/l5kit#156]
OS: Windows 8.1
Python version: 3.7.5

Description: I guess it is due to multiprocessing. I am not able to run this on my local computer.

>>>Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit
(AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from l5kit.dataset import AgentDataset, EgoDataset
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Prasad\AppData\Local\Programs\Python\Python37\lib\site-packages
\l5kit\dataset\__init__.py", line 1, in <module>
    from .agent import AgentDataset
  File "C:\Users\Prasad\AppData\Local\Programs\Python\Python37\lib\site-packages
\l5kit\dataset\agent.py", line 12, in <module>
    from .select_agents import TH_DISTANCE_AV, TH_EXTENT_RATIO, TH_YAW_DEGREE, s
elect_agents
  File "C:\Users\Prasad\AppData\Local\Programs\Python\Python37\lib\site-packages
\l5kit\dataset\select_agents.py", line 21, in <module>
    multiprocessing.set_start_method("fork", force=True)  # this fix loop in pyt
hon 3.8 on MacOS
  File "C:\Users\Prasad\AppData\Local\Programs\Python\Python37\lib\multiprocessi
ng\context.py", line 246, in set_start_method
    self._actual_context = self.get_context(method)
  File "C:\Users\Prasad\AppData\Local\Programs\Python\Python37\lib\multiprocessi
ng\context.py", line 238, in get_context
    return super().get_context(method)
  File "C:\Users\Prasad\AppData\Local\Programs\Python\Python37\lib\multiprocessi
ng\context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'
>>>

**Comment by lucabergamini** [comment]
Hi @PrasadNR,
This has been fixed in master, which version are you running?  
If you're on a release and don't want to change it, you can use the temporary fix in  #129.

Closing this as duplicated.

**Comment by PrasadNR** [comment]
> Name: l5kit
Version: 1.0.6
Summary: Lyft Autonomous Vehicle Research library
Home-page: https://github.com/lyft/l5kit
Author: Lyft Level 5
Author-email: l5kit@lyft.com
License: apache2
Location: c:\users\prasad\appdata\local\programs\python\python37\lib\site-packag
es
Requires: torchvision, numpy, setuptools, opencv-contrib-python-headless, pymap3
d, torch, ipywidgets, tqdm, imageio, notebook, zarr, transforms3d, ptable, pyyam
l, protobuf, matplotlib, scipy
Required-by:

But, let me try upgrading the l5kit. Thank you so much for the quick reply!

**Comment by PrasadNR** [comment]
No luck with `pip uninstall l5kit` followed by `pip install l5kit`. Also, I tried `pip install -U l5kit`. I am still getting the same error. So, how am I supposed to install using the master on Windows?

**Comment by lucabergamini** [comment]
> No luck with `pip uninstall l5kit` followed by `pip install l5kit`

Yes, that will just install the latest release, but not the latest master.



> Because, I am not able to install using https://github.com/lyft/l5kit#3-install-l5kit on Windows.

Why is that? Any specific error?

**Comment by PrasadNR** [comment]
> 
> E:\>git clone https://github.com/lyft/l5kit.git ./
> fatal: destination path '.' already exists and is not an empty directory.
> 
> E:\>git clone https://github.com/lyft/l5kit.git
> Cloning into 'l5kit'...
> remote: Enumerating objects: 234, done.
> remote: Counting objects: 100% (234/234), done.
> remote: Compressing objects: 100% (119/119), done.
> remote: Total 4089 (delta 145), reused 175 (delta 115), pack-reused 3855
> Receiving objects: 100% (4089/4089), 12.64 MiB | 2.49 MiB/s, done.
> Resolving deltas: 100% (2909/2909), done.
> 
> E:\>cd l5kit
> 
> E:\l5kit>pipenv sync --dev
> 'pipenv' is not recognized as an internal or external command,
> operable program or batch file.
> 
> E:\l5kit>pip install pipenv
> Collecting pipenv
>   Downloading pipenv-2020.8.13-py2.py3-none-any.whl (3.9 MB)
>      |████████████████████████████████| 3.9 MB 386 kB/s
> Requirement already satisfied: setuptools>=36.2.1 in c:\users\prasad\appdata\loc
> al\programs\python\python37\lib\site-packages (from pipenv) (41.2.0)
> Requirement already satisfied: pip>=18.0 in c:\users\prasad\appdata\local\progra
> ms\python\python37\lib\site-packages (from pipenv) (20.2.3)
> Collecting virtualenv-clone>=0.2.5
>   Downloading virtualenv_clone-0.5.4-py2.py3-none-any.whl (6.6 kB)
> Collecting virtualenv
>   Downloading virtualenv-20.0.31-py2.py3-none-any.whl (4.9 MB)
>      |████████████████████████████████| 4.9 MB 2.2 MB/s
> Requirement already satisfied: certifi in c:\users\prasad\appdata\local\programs
> \python\python37\lib\site-packages (from pipenv) (2019.11.28)
> Requirement already satisfied: appdirs<2,>=1.4.3 in c:\users\prasad\appdata\loca
> l\programs\python\python37\lib\site-packages (from virtualenv->pipenv) (1.4.4)
> Requirement already satisfied: six<2,>=1.9.0 in c:\users\prasad\appdata\local\pr
> ograms\python\python37\lib\site-packages (from virtualenv->pipenv) (1.13.0)
> Requirement already satisfied: importlib-metadata<2,>=0.12; python_version < "3.
> 8" in c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages (
> from virtualenv->pipenv) (1.5.0)
> Collecting distlib<1,>=0.3.1
>   Downloading distlib-0.3.1-py2.py3-none-any.whl (335 kB)
>      |████████████████████████████████| 335 kB 3.3 MB/s
> Collecting filelock<4,>=3.0.0
>   Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
> Requirement already satisfied: zipp>=0.5 in c:\users\prasad\appdata\local\progra
> ms\python\python37\lib\site-packages (from importlib-metadata<2,>=0.12; python_v
> ersion < "3.8"->virtualenv->pipenv) (3.1.0)
> Installing collected packages: virtualenv-clone, distlib, filelock, virtualenv,
> pipenv
> Successfully installed distlib-0.3.1 filelock-3.0.12 pipenv-2020.8.13 virtualenv
> -20.0.31 virtualenv-clone-0.5.4
> 
> E:\l5kit>pipenv sync --dev
> [LockfileNotFound]:   File "c:\users\prasad\appdata\local\programs\python\python
> 37\lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
> [LockfileNotFound]:       return callback(*args, **kwargs)
> [LockfileNotFound]:   File "c:\users\prasad\appdata\local\programs\python\python
> 37\lib\site-packages\pipenv\vendor\click\decorators.py", line 73, in new_func
> [LockfileNotFound]:       return ctx.invoke(f, obj, *args, **kwargs)
> [LockfileNotFound]:   File "c:\users\prasad\appdata\local\programs\python\python
> 37\lib\site-packages\pipenv\vendor\click\core.py", line 610, in invoke
> [LockfileNotFound]:       return callback(*args, **kwargs)
> [LockfileNotFound]:   File "c:\users\prasad\appdata\local\programs\python\python
> 37\lib\site-packages\pipenv\vendor\click\decorators.py", line 21, in new_func
> [LockfileNotFound]:       return f(get_current_context(), *args, **kwargs)
> [LockfileNotFound]:   File "c:\users\prasad\appdata\local\programs\python\python
> 37\lib\site-packages\pipenv\cli\command.py", line 693, in sync
> [LockfileNotFound]:       pypi_mirror=state.pypi_mirror,
> [LockfileNotFound]:   File "c:\users\prasad\appdata\local\programs\python\python
> 37\lib\site-packages\pipenv\core.py", line 2869, in do_sync
> [LockfileNotFound]:       raise exceptions.LockfileNotFound("Pipfile.lock")
> ERROR: Pipfile.lock not found! You need to run $ pipenv lock before you can cont
> inue.
> 
> E:\l5kit>pip install -e .[dev]
> ERROR: File "setup.py" not found. Directory cannot be installed in editable mode
> : E:\l5kit
> 
> E:\l5kit>

I have listed all that I have tried. I am not sure why there is a problem with Pipfile.lock. Anyways, for now, I think I will continue to use Google Colab and once I run sample dataset, I will change the sample_agents.py fork method to spawn and try it on my computer. Thank you! I really appreciate your timely response!

**Comment by lucabergamini** [comment]
can you try this:
`git clone https://github.com/lyft/l5kit.git`
`cd l5kit/l5kit`
`pip install -e .[dev]`
?

The guide is missing a `cd` :( I'll update it

**Comment by lucabergamini** [comment]
> It was literally saying "run $ `pipenv lock` before you can continue". This is the first time I am using Pipenv. So, this is a mistake from my end. I apologise.

Skip the deterministic build, I don't think it will work on Windows anyway

**Comment by lucabergamini** [comment]
> The guide is missing a `cd` :( I'll update it

To give you some context:
you need to run the command from where the `setup.py` is

**Comment by PrasadNR** [comment]
> 
> 
> can you try this:
> `git clone https://github.com/lyft/l5kit.git`
> `cd l5kit/l5kit`
> `pip install -e .[dev]`
> ?
> 
> The guide is missing a `cd` :( I'll update it

Oh yes! This works! Let me try the agent motion prediction and visualisation examples.

**Comment by lucabergamini** [comment]
> Update: Now, all imports of both examples work like a breeze! Thanks @lucabergamini .

My job :) glad it works now
